#!/bin/bash

#	Fronius Smartmeter
#	Setup script (install/uninstall)
#
# this script will accept the following commands on the command line:
#	setup install
#	setup uninstall
#	setup reinstall (used to reinstall after Venus OS update)

packageLogFile="/var/log/victron_easton/current"



# GitHub account info - fill in as appropriate
# to include this package in SetupHelper automatic updates
packageGitHubUser="florian-mitb"
packageGitHubBranch="main"

#### end of lines to include SetupHelper
# tell CommonResources to:
#	prompt for install/uninstall
#	auto install or auto uninstall
#	then exit
#	IncludeHelpers will NOT return here !

standardPromptAndActions='yes'

#### following lines incorporate helper resources into this script
pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
pkgRoot=$( dirname $pkgDir )
if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
	source "$pkgDir/HelperResources/IncludeHelpers"
elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi
#### end of lines to include helper resources
